language: ruby

sudo:
    false

rvm:
  - 2.1
  - 2.2.7
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile

before_script:
  - git submodule update --remote --recursive

script:
  - bundle exec rake spec:ci
  - bundle exec rake spec:api
  - bundle exec rake spec:testrunner

matrix:
  exclude:
  - rvm: 2.1
    gemfile: gemfiles/rails_50.gemfile
  - rvm: 2.1
    gemfile: gemfiles/rails_51.gemfile
